spring:
  application:
    name: inventario-service
  datasource:
    url: jdbc:postgresql://postgres:5432/inventario_db
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# URL del microservicio de productos
productos:
  service:
    url: http://localhost:8081
    api-key: LINK_TIC

security:
  api-key: LINK_TIC


server:
  port: 8082
